//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palkin_0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Materials_in_products = new HashSet<Materials_in_products>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> cost_for_unit { get; set; }
        public Nullable<int> amount_in_stock { get; set; }
        public Nullable<int> id_material_type { get; set; }
    
        public virtual Material_type Material_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials_in_products> Materials_in_products { get; set; }
    }
}
