//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palkin_0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Partner_products_request = new HashSet<Partner_products_request>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_partner_type { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
        public Nullable<int> rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request> Partner_products_request { get; set; }
        public virtual Partner_type Partner_type { get; set; }
    }
}
