//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palkin_0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_request
    {
        public int id { get; set; }
        public string id_product { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
